#ifndef VERTEX_H_INCLUDED
#define VERTEX_H_INCLUDED

enum {
    VERTEX_ATTRIB_POSITION = 0,
    VERTEX_ATTRIB_TEXCOORD = 1,
    VERTEX_ATTRIB_NORMAL = 2,
    VERTEX_ATTRIB_COLOR = 3,
};

enum vertex_format {
    VERTEX_FORMAT_POSITION = (1 << VERTEX_ATTRIB_POSITION),
    VERTEX_FORMAT_TEXCOORD = (1 << VERTEX_ATTRIB_TEXCOORD),
    VERTEX_FORMAT_NORMAL   = (1 << VERTEX_ATTRIB_NORMAL),
    VERTEX_FORMAT_COLOR    = (1 << VERTEX_ATTRIB_COLOR),
};

long vertex_size(int format);

#endif
