name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v*  # no need to waste builds on tagged releases

jobs:
  build_linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Update package listing
        run: sudo apt update
      - name: Install dependencies
        run: sudo apt install libglfw3-dev
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Build project
        run: make
  build_macos:
    name: macOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Build project
        run: make LDLIBS='-Lvendor/lib64/macos/ -lglfw3 -framework Cocoa -framework IOKit'
  build_windows:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Build project
        run: scripts\shell_enterprise.bat && scripts\build.bat
        shell: cmd
